# Generated by Django 2.2.2 on 2019-07-26 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='Rad_accu_prev1',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
