# Generated by Django 2.2.2 on 2019-07-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0002_auto_20190726_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='Rad_accu_prev1',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
