# Generated by Django 2.2.2 on 2019-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0003_auto_20190726_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='P_accu',
            field=models.DecimalField(decimal_places=2, help_text='Bla', max_digits=6),
        ),
    ]
