# Generated by Django 2.2.2 on 2019-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0004_auto_20190727_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='P_accu',
            field=models.DecimalField(decimal_places=2, help_text='Lluvias acumuladas (mms)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Rad_accu_prev1',
            field=models.DecimalField(decimal_places=2, help_text='Radiación acumulada un mes previo a la cosecha (µmol·m²s-1)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datos',
            name='T_avg_prev',
            field=models.DecimalField(decimal_places=2, help_text='Temperatura promedio un mes previo a la cosecha (C)', max_digits=6),
        ),
    ]
