# Generated by Django 2.2.2 on 2019-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0005_auto_20190727_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='P_accu',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Rad_accu_prev1',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='datos',
            name='T_avg_prev',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
